### PR TITLE
Fix login/signin buttons, front-end work

### PR DESCRIPTION
**Pull request by sophstad**
Fixes issue #12

### CODE REVIEW

**Comment by sophstad** [comment]
@TheBatmanofButler wanna check this over?

**Comment by sophstad** [comment]
@TheBatmanofButler wanna check this over?

**Comment by sophstad** [comment]
Thanks @jcbartlett25 this was a blocker !!! ❤️

**Comment by jcbartlett25** [comment]
No problem! Be sure to raise any blockers in our next standup so we don't remain stuck for 8 years again :smiley:

**Pull request merged**
